- name: rpm
  shell: "rpm -Uvh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm"
  ignore_errors: yes

- name: install nginx
  yum:
       name: nginx
       state: latest
       update_cache: yes

- name: start nginx
  service:
           name: nginx
           state: started
           enabled: yes 

- name: Delete default site
  file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

- name: Install nginx configuration
  template:
            src: nginx_wordpress.conf
            dest: /etc/nginx/conf.d/{{ name_site_config }}
  notify: NGINX restart

- name: Change config
  lineinfile: 
              dest={{ item.dest }}
              regexp={{ item.regexp }}
              line={{ item.line }}

  with_items:
              - { dest: '/etc/php.ini' , regexp: ';cgi.fix_pathinfo=1' , line: 'cgi.fix_pathinfo=0' }
              - { dest: '/etc/php-fpm.d/www.conf' , regexp: 'listen =' , line: 'listen = /var/run/php-fpm/php-fpm.sock' }
              - { dest: '/etc/php-fpm.d/www.conf' , regexp: ';listen.owner = nobody' , line: 'listen.owner = nobody' }
              - { dest: '/etc/php-fpm.d/www.conf' , regexp: ';listen.group = nobody' , line: 'listen.group = nobody' }
              - { dest: '/etc/php-fpm.d/www.conf' , regexp: 'user = apache' , line: 'user = nginx' }
              - { dest: '/etc/php-fpm.d/www.conf' , regexp: 'group = apache' , line: 'group = nginx' }              

- name: PHP-FPM start
  service:
           name: php-fpm
           state: started
           enabled: yes
