- name: Install PHP
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
              - php
              - php-fpm
              - php-mysql
              - php-memcache
              - php-memcached
              - php-mcrypt
              - php-cgi
              - php-gd
              - php-curl
              - php-xmlrpc
  notify: apache restart
  
  


